name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    # 1. Konfigurasi Service Container PostgreSQL (Database Test Temporer)
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: ci_user_test
          POSTGRES_PASSWORD: ci_password_test
          POSTGRES_DB: forumapi_test_ci
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install

      # 2. Menjalankan Migrasi (Membuat Tabel)
      - name: Run Database Migrations
        run: node-pg-migrate up
        env:
          PGHOST: localhost
          PGUSER: ci_user_test
          PGPASSWORD: ci_password_test
          PGDATABASE: forumapi_test_ci
          PGPORT: 5432

      # 3. Menjalankan Semua Pengujian
      - name: Run Tests
        run: npm test
        env:
          PGHOST_TEST: localhost
          PGUSER_TEST: ci_user_test
          PGPASSWORD_TEST: ci_password_test
          PGDATABASE_TEST: forumapi_test_ci
          PGPORT_TEST: 5432
          NODE_ENV: test
          ACCESS_TOKEN_KEY: secret
          REFRESH_TOKEN_KEY: terces
